// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

AgeKey createKey() => RustLib.instance.api.crateApiFunctionsCreateKey();

String encryptString({required String message, required String publicKey}) =>
    RustLib.instance.api.crateApiFunctionsEncryptString(
      message: message,
      publicKey: publicKey,
    );

String decryptString({
  required String ciphertext,
  required String privateKey,
}) => RustLib.instance.api.crateApiFunctionsDecryptString(
  ciphertext: ciphertext,
  privateKey: privateKey,
);
